name: Core
main: me.oggunderscore.Core.Main
version: 1.0
api-version: 1.13
author: IgnitedMC Development
description: IgnitedMC's Main Core
commands:
    invsee:
        description: See a players inventory
    tp:
        description: Teleport to someone
    givegold:
        description: Give Gold!
    update:
        description: Send a update notification!
    poke:
        description: Poke a player!
    forceleave:
        description: Make Everyone Force Leave!
    oggclear:
        description: Clear the chat!
    urf:
        description: ez
    heal:
        description: Heal yourself or others!
    fly:
        description: Toggle fly on and off
    ping:
        description: Checks a player's ping.
    vanish:
        aliases: [v]
        description: vanish yourself.
    broadcast:
        aliases: [bc]
        description: Broadcast a message to everyone.
permissions:
    oggcore.staff:
        default: false